- id: jira_branch_name
  name: Check branch name include ticket id
  description: Check branch name include ticket id
  entry: jira_branch_name.sh
  pass_filenames: false
  language: script
- id: add_jira_ref_to_commit_msg
  name: add jira tef as prefix
  entry: add_jira_ref_to_commit_msg.sh
  pass_filenames: false
  language: script
